[package]
edition = "2024"
name = "abs_buff"
version = "0.3.0"

description = "ABStraction of BUFFered IO"
repository = "https://github.com/ljsnogard/abs_buff"
keywords = ["IO", "buffer"]
categories = ["no-std"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
anylr = { git = "https://gitee.com/lino_snsalias/anylr.rs.git", branch = "dev/0.2.0" }
abs_iter = { git = "https://gitee.com/lino_snsalias/abs_iter.git" }
abs_cancel = { git = "https://gitee.com/lino_snsalias/abs_cancel-rs.git" }
gen_mcf_macro = { git = "https://gitee.com/lino_snsalias/gen_mcf_macro.rs.git", branch = "dev/0.3.0" }

funty = { version = "3.0.0-rc2", default-features = false }
